fg: fg::Vec3 Class Reference
fg::Vec3 Class Reference
#include <vec3.h>
Public Member Functions
Vec3 (const vcg::Point3d &p)
Vec3 (double x, double y, double z)
double getX ()
void setX (double x)
double getY ()
void setY (double y)
double getZ ()
void setZ (double z)
void normalise ()
Vec3 operator+ (const Vec3 &b) const
Vec3 operator* (double d) const
Constructor & Destructor Documentation
fg::Vec3::Vec3 (const vcg::Point3d & p) [inline]
Referenced by operator*(), and operator+().
fg::Vec3::Vec3 (double x, double y, double z)
Member Function Documentation
double fg::Vec3::getX () [inline]
double fg::Vec3::getY () [inline]
double fg::Vec3::getZ () [inline]
void fg::Vec3::normalise ()
Vec3 fg::Vec3::operator* (double d) const
References Vec3().
Vec3 fg::Vec3::operator+ (const Vec3 & b) const
References Vec3().
void fg::Vec3::setX (double x) [inline]
void fg::Vec3::setY (double y) [inline]
void fg::Vec3::setZ (double z) [inline]
The documentation for this class was generated from the following files:
vec3.h
vec3.cpp