fg: fg::Extrude Class Reference
fg::Extrude Class Reference
#include <meshoperators_vcg.h>
Public Types
typedef MeshImpl MyMesh
typedef MyMesh::VertexType Vertex
typedef MyMesh::VertexPointer VertexPointer
typedef MyMesh::FaceType Face
typedef MyMesh::FacePointer FacePointer
typedef std::vector
< VertexPointer * > VPUpdateList
Static Public Member Functions
static std::set< VertexPointer > extrude (MyMesh *m, Vertex *&v, VPUpdateList &vpul, int width, vcg::Point3d direction, double length, double expand)
static bool isEdgeLoop (std::vector< VertexPointer > &loop)
Member Typedef Documentation
typedef MyMesh::FaceType fg::Extrude::Face
typedef MyMesh::FacePointer fg::Extrude::FacePointer
typedef MeshImpl fg::Extrude::MyMesh
typedef MyMesh::VertexType fg::Extrude::Vertex
typedef MyMesh::VertexPointer fg::Extrude::VertexPointer
typedef std::vector<VertexPointer*> fg::Extrude::VPUpdateList
Member Function Documentation
std::set< Extrude::VertexPointer > fg::Extrude::extrude (MyMesh * m, Vertex *& v, VPUpdateList & vpul, int width, vcg::Point3d direction, double length, double expand) [static]
References isEdgeLoop().
Referenced by extrude().
static bool fg::Extrude::isEdgeLoop (std::vector< VertexPointer > & loop) [static]
Referenced by extrude().
The documentation for this class was generated from the following files:
meshoperators_vcg.h
meshoperators_vcg.cpp