fg: FooProxy Class Reference
FooProxy Class Reference
Public Member Functions
FooProxy (Foo *f)
int getX () const
void setX (int x)
int getOX () const
Constructor & Destructor Documentation
FooProxy::FooProxy (Foo * f) [inline]
Member Function Documentation
int FooProxy::getOX () const [inline]
References Proxy< Foo >::constImpl(), and Foo::ox.
Referenced by operator<<().
int FooProxy::getX () const [inline]
References Proxy< Foo >::constImpl(), and Foo::x.
Referenced by doBindings(), and operator<<().
void FooProxy::setX (int x) [inline]
References Proxy< Foo >::pImpl(), and Foo::x.
Referenced by doBindings().
The documentation for this class was generated from the following file:
lb_refcounted.cpp