fg: B Class Reference
B Class Reference
Public Member Functions
std::list< A * > getList ()
std::list< A * > & getListR ()
ListOfA * getNewList ()
boost::shared_ptr< ListOfA > getNewSPList ()
std::list
< boost::reference_wrapper< A > > getListB ()
int size ()
A & get (int i)
Public Attributes
std::vector< A > list
Member Function Documentation
A& B::get (int i) [inline]
References list.
Referenced by doBindings(), and main().
std::list<A*> B::getList () [inline]
References list.
Referenced by doBindings(), and main().
std::list<boost::reference_wrapper<A> > B::getListB () [inline]
References list.
Referenced by doBindings(), and main().
std::list<A*>& B::getListR () [inline]
References list.
Referenced by doBindings().
ListOfA* B::getNewList () [inline]
References list.
Referenced by doBindings().
boost::shared_ptr<ListOfA> B::getNewSPList () [inline]
References list.
Referenced by doBindings().
int B::size () [inline]
References list.
Referenced by doBindings().
Member Data Documentation
std::vector<A> B::list
Referenced by doBindings(), get(), getList(), getListB(), getListR(), getNewList(), getNewSPList(), main(), printB(), and size().
The documentation for this class was generated from the following file:
luabindstl.cpp