fg: fg::VertexProxy Class Reference
fg::VertexProxy Class Reference
#include <vertex.h>
Public Member Functions
VertexProxy (VertexImpl *vi)
~VertexProxy ()
Vec3 getPos () const
void setPos (Vec3 v)
void setPos (double x, double y, double z)
Vec3 getN ()
Detailed Description
A VertexProxy has a number of purposes:
Provides access to the underlying vcg::Vertex implementation
Adds helper methods for the lua bindings
TODO: Add helper methods for accessing custom data
Constructor & Destructor Documentation
fg::VertexProxy::VertexProxy (VertexImpl * vi)
fg::VertexProxy::~VertexProxy ()
Member Function Documentation
Vec3 fg::VertexProxy::getN ()
References fg::Proxy< VertexImpl >::pImpl().
Vec3 fg::VertexProxy::getPos () const
References fg::Proxy< VertexImpl >::constImpl().
void fg::VertexProxy::setPos (double x, double y, double z)
References fg::Proxy< VertexImpl >::pImpl().
void fg::VertexProxy::setPos (Vec3 v)
References fg::Proxy< VertexImpl >::pImpl().
The documentation for this class was generated from the following files:
vertex.h
vertex.cpp