fg: FooContainer Class Reference
FooContainer Class Reference
Public Member Functions
Foo * newFoo (int d)
Foo * select (int i)
FooProxy selectP (int i)
boost::shared_ptr< FooProxy > selectP2 (int i)
void shuffle ()
void shuffleAndUpdateProxies ()
void updateProxyRefs ()
void doSomethingThatDeletesSomeFoos ()
Member Function Documentation
void FooContainer::doSomethingThatDeletesSomeFoos () [inline]
Referenced by deleteSomeFoos().
Foo* FooContainer::newFoo (int d) [inline]
References Foo::ox, and Foo::x.
Referenced by main(), shuffle(), and shuffleAndUpdateProxies().
Foo* FooContainer::select (int i) [inline]
Referenced by select1(), select2(), selectP(), and selectP2().
FooProxy FooContainer::selectP (int i) [inline]
References select().
Referenced by select3().
boost::shared_ptr<FooProxy> FooContainer::selectP2 (int i) [inline]
References select().
Referenced by selectP2().
void FooContainer::shuffle () [inline]
References newFoo(), Foo::ox, and Foo::x.
Referenced by shuffle().
void FooContainer::shuffleAndUpdateProxies () [inline]
References newFoo(), Foo::ox, updateProxyRefs(), and Foo::x.
Referenced by shuffleAndUpdateProxies().
void FooContainer::updateProxyRefs () [inline]
Referenced by shuffleAndUpdateProxies().
The documentation for this class was generated from the following file:
lb_refcounted.cpp