fg: fg::Universe Class Reference
fg::Universe Class Reference
#include <universe.h>
Public Types
typedef std::list
< boost::shared_ptr< Mesh > > MeshContainer
Public Member Functions
Universe ()
~Universe ()
void addScriptDirectory (std::string scriptPath)
void loadScript (std::string scriptName)
Load an fg script.
void addMesh (boost::shared_ptr< Mesh > m)
MeshContainer & meshes ()
void update (double dt)
double time () const
Returns the current time in the universe.
Detailed Description
A universe contains all the objects, meshes, scripts, etc.
Member Typedef Documentation
typedef std::list<boost::shared_ptr<Mesh> > fg::Universe::MeshContainer
Constructor & Destructor Documentation
fg::Universe::Universe ()
References fg::loadLuaBindings().
fg::Universe::~Universe ()
Member Function Documentation
void fg::Universe::addMesh (boost::shared_ptr< Mesh > m)
void fg::Universe::addScriptDirectory (std::string scriptPath)
Referenced by main().
void fg::Universe::loadScript (std::string scriptName)
Load an fg script.
This method loads a lua script and executes its setup function. It will also add it to the list of scripts to be updated if it has an update function.
References fg::error().
Referenced by main().
Universe::MeshContainer & fg::Universe::meshes ()
Referenced by main().
double fg::Universe::time () const
Returns the current time in the universe.
< Returns the current time in the universe
void fg::Universe::update (double dt)
Update all objects in the universe by a specified time increment.
References fg::error().
Referenced by main().
The documentation for this class was generated from the following files:
universe.h
universe.cpp