fg: fg::Mesh Class Reference
fg::Mesh Class Reference
#include <mesh.h>
Classes
class Primitives
Public Types
typedef std::list
< boost::shared_ptr
< VertexProxy > > VertexSet
Public Member Functions
~Mesh ()
boost::shared_ptr< VertexSet > selectAllVertices ()
boost::shared_ptr< VertexProxy > selectRandomVertex ()
void getBounds (double &minx, double &miny, double &minz, double &maxx, double &maxy, double &maxz)
void subdivide (int levels)
Perform smooth subdivision on the mesh.
void sync ()
Sync will make sure all the topology, normals, etc are fixed..
void drawGL ()
MeshImpl * _impl ()
return the VCG implementation in this mesh
VertexProxyList * _vpl ()
return the VertexProxyList, so vertices can get their references updated
Member Typedef Documentation
typedef std::list<boost::shared_ptr<VertexProxy> > fg::Mesh::VertexSet
Constructor & Destructor Documentation
fg::Mesh::~Mesh ()
Member Function Documentation
MeshImpl * fg::Mesh::_impl ()
return the VCG implementation in this mesh
Low-level implementation access. Only use these if you know what you are doing.
VertexProxyList * fg::Mesh::_vpl ()
return the VertexProxyList, so vertices can get their references updated
void fg::Mesh::drawGL ()
References sync().
void fg::Mesh::getBounds (double & minx, double & miny, double & minz, double & maxx, double & maxy, double & maxz)
boost::shared_ptr< Mesh::VertexSet > fg::Mesh::selectAllVertices ()
Select all the vertices TODO: Update to new VertexProxy system
Returns:
References fg::VertexProxyList::add().
boost::shared_ptr< VertexProxy > fg::Mesh::selectRandomVertex ()
Returns:
A random vertex
References fg::VertexProxyList::add(), and fg::random().
void fg::Mesh::subdivide (int levels)
Perform smooth subdivision on the mesh.
void fg::Mesh::sync ()
Sync will make sure all the topology, normals, etc are fixed..
Referenced by drawGL(), fg::Mesh::Primitives::Icosahedron(), and fg::Mesh::Primitives::Sphere().
The documentation for this class was generated from the following files:
mesh.h
mesh.cpp