fg: vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType > Class Template Reference
vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType > Class Template Reference
#include <export_obj_point3d.h>
Public Types
enum SaveError {
E_NOERROR, E_CANTOPENFILE, E_CANTCLOSEFILE, E_UNESPECTEDEOF,
E_ABORTED, E_NOTDEFINITION, E_NOTVEXTEXVALID, E_NOTFACESVALID
}
typedef SaveMeshType::FaceIterator FaceIterator
typedef
SaveMeshType::VertexIterator VertexIterator
typedef SaveMeshType::VertexType VertexType
Static Public Member Functions
static const char * ErrorMsg (int error)
static int GetExportMaskCapability ()
static int Save (SaveMeshType &m, const char *filename, int mask, CallBackPos *cb=0)
static int GetIndexVertex (SaveMeshType &m, VertexType *p)
static int GetIndexVertexTexture (std::map< TexCoord2< float >, int > &mapTexToInt, const vcg::TexCoord2< float > &wt)
static int GetIndexVertexNormal (SaveMeshType &, std::map< Point3d, int > &mapNormToInt, const Point3d &norm)
static void WriteFacesElement (FILE *fp, int v, int vt, int vn)
static bool AddNewTextureCoord (std::map< vcg::TexCoord2< float >, int > &m, const vcg::TexCoord2< float > &wt, int value)
static bool AddNewNormalVertex (std::map< Point3d, int > &m, Point3d &n, int value)
static int WriteMaterials (std::vector< Material > &materialVec, const char *filename, CallBackPos *cb=0)
template<class SaveMeshType>
class vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >
Member Typedef Documentation
template<class SaveMeshType> typedef SaveMeshType::FaceIterator vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::FaceIterator
template<class SaveMeshType> typedef SaveMeshType::VertexIterator vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::VertexIterator
template<class SaveMeshType> typedef SaveMeshType::VertexType vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::VertexType
Member Enumeration Documentation
template<class SaveMeshType> enum vcg::tri::io::ExporterOBJ_Point3d::SaveError
Enumerator:
E_NOERROR
E_CANTOPENFILE
E_CANTCLOSEFILE
E_UNESPECTEDEOF
E_ABORTED
E_NOTDEFINITION
E_NOTVEXTEXVALID
E_NOTFACESVALID
Member Function Documentation
template<class SaveMeshType> static bool vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::AddNewNormalVertex (std::map< Point3d, int > & m, Point3d & n, int value) [inline, static]
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
template<class SaveMeshType> static bool vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::AddNewTextureCoord (std::map< vcg::TexCoord2< float >, int > & m, const vcg::TexCoord2< float > & wt, int value) [inline, static]
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
template<class SaveMeshType> static const char* vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::ErrorMsg (int error) [inline, static]
template<class SaveMeshType> static int vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetExportMaskCapability () [inline, static]
template<class SaveMeshType> static int vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetIndexVertex (SaveMeshType & m, VertexType * p) [inline, static]
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
template<class SaveMeshType> static int vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetIndexVertexNormal (SaveMeshType & , std::map< Point3d, int > & mapNormToInt, const Point3d & norm) [inline, static]
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
template<class SaveMeshType> static int vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetIndexVertexTexture (std::map< TexCoord2< float >, int > & mapTexToInt, const vcg::TexCoord2< float > & wt) [inline, static]
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
template<class SaveMeshType> static int vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save (SaveMeshType & m, const char * filename, int mask, CallBackPos * cb = 0) [inline, static]
References vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::AddNewNormalVertex(), vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::AddNewTextureCoord(), vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::E_ABORTED, vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::E_CANTOPENFILE, vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::E_NOERROR, vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::E_NOTVEXTEXVALID, vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetIndexVertex(), vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetIndexVertexNormal(), vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::GetIndexVertexTexture(), vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::WriteFacesElement(), and vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::WriteMaterials().
Referenced by main().
template<class SaveMeshType> static void vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::WriteFacesElement (FILE * fp, int v, int vt, int vn) [inline, static]
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
template<class SaveMeshType> static int vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::WriteMaterials (std::vector< Material > & materialVec, const char * filename, CallBackPos * cb = 0) [inline, static]
References vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::E_ABORTED, and vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::E_NOERROR.
Referenced by vcg::tri::io::ExporterOBJ_Point3d< SaveMeshType >::Save().
The documentation for this class was generated from the following file:
export_obj_point3d.h