fg: fg::Mesh::Primitives Class Reference
fg::Mesh::Primitives Class Reference
#include <mesh.h>
Static Public Member Functions
static boost::shared_ptr< Mesh > Icosahedron ()
static boost::shared_ptr< Mesh > Sphere ()
Member Function Documentation
boost::shared_ptr< Mesh > fg::Mesh::Primitives::Icosahedron () [static]
References fg::Mesh::sync().
Referenced by main().
boost::shared_ptr< Mesh > fg::Mesh::Primitives::Sphere () [static]
References fg::Mesh::sync().
The documentation for this class was generated from the following files:
mesh.h
mesh.cpp